{% set name = "f90wrap" %}
{% set version = "0.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7f5eda60efbf9ce5bdffb0c864922910c2766bf9eefd3af290c81051226f7fc7

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - setuptools
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - numpy <1.24,>=1.13
  run:
    - python
    - numpy <1.24,>=1.13

test:
  imports:
    - f90wrap
  commands:
    - f90wrap -h
    - f2py-f90wrap -h
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jameskermode/f90wrap
  license: GPL-2.0
  license_file: LICENSE.txt
  summary: Fortran to Python interface generator with derived type support.

extra:
  recipe-maintainers:
    - jameskermode
    - ocefpaf
    - jan-janssen
