{% set version = "0.1.5" %}

package:
  name: f90wrap
  version: {{ version }}

source:
  url: https://github.com/jameskermode/f90wrap/archive/v{{ version }}.tar.gz
  sha256: d78125c1679d68f500f83c9ece8cd3c0eeda7d1f1490c3a16a1392e0ed8b298b

build:
  number: 1
  skip: True  # [win]
  script:
    - export LDFLAGS="-undefined dynamic_lookup -bundle"  # [osx]
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - f90wrap
  commands:
    - f90wrap -h
    - f2py-f90wrap -h
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/jameskermode/f90wrap
  license: GPL-2.0
  license_file: LICENSE.txt
  summary: 'Fortran to Python interface generator with derived type support.'

extra:
  recipe-maintainers:
    - jameskermode
    - ocefpaf
