{% set version = "0.1.5" %}

package:
  name: f90wrap
  version: {{ version }}

source:
  fn: f90wrap-{{ version }}.tar.gz
  url: https://github.com/jameskermode/f90wrap/archive/v{{ version }}.tar.gz
  sha256: d78125c1679d68f500f83c9ece8cd3c0eeda7d1f1490c3a16a1392e0ed8b298b

build:
  number: 1000
  skip: True  # [win]
  script:
    - export LDFLAGS="-undefined dynamic_lookup -bundle"  # [osx]
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy 1.7.*  # [py27]
    - numpy 1.8.*  # [py35 or py36]
    - gcc  # [not win]
  run:
    - python
    - numpy >=1.7  # [py27]
    - numpy >=1.8  # [py35 or py36]
    - libgcc  # [linux]
    - libgfortran  # [osx]

test:
  imports:
    - f90wrap
  commands:
    - f90wrap -h
    - f2py-f90wrap -h
    - conda inspect linkages -p $PREFIX f90wrap  # [not win]
    - conda inspect objects -p $PREFIX f90wrap  # [osx]

about:
  home: https://github.com/jameskermode/f90wrap
  license: GPL-2.0
  license_file: LICENSE.txt
  summary: 'Fortran to Python interface generator with derived type support.'

extra:
  recipe-maintainers:
    - jameskermode
    - ocefpaf
