{% set name = "f90wrap" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a7c735b493dba21c0c3379d4693901c49129a52f034e111e0f35a6fe605792f1
  patches:
    - numpy.patch

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - setuptools
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - numpy >=1.13
    - meson-python
  run:
    - python
    - numpy >=1.13

test:
  imports:
    - f90wrap
  commands:
    - f90wrap -h
    - f2py-f90wrap -h
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jameskermode/f90wrap
  license: GPL-2.0
  license_file: LICENSE.txt
  summary: Fortran to Python interface generator with derived type support.

extra:
  recipe-maintainers:
    - jameskermode
    - ocefpaf
    - jan-janssen
