{% set name = "f90wrap" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c9f08768fe7e9d60de9e913e30909fa1bdc67828f49dffd7149089703d74836

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - setuptools
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
  host:
    - python
    - python-build
    - pip
    - numpy
    - meson-python
  run:
    - python
    - numpy
    - packaging

test:
  imports:
    - f90wrap
  commands:
    - f90wrap -h
    - f2py-f90wrap -h
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jameskermode/f90wrap
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  summary: Fortran to Python interface generator with derived type support.

extra:
  recipe-maintainers:
    - jameskermode
    - ocefpaf
    - jan-janssen
